#!/usr/bin/env bash
#
# Mike Word Add-in — one-command local dev setup + launch.
#
#   bash word-addin/scripts/dev.sh
#
# What it does (idempotent — safe to re-run):
#   1. Verifies Node is available.
#   2. Reads the backend origin (NEXT_PUBLIC_API_BASE_URL) from
#      frontend/.env.local and writes word-addin/.env — the webpack
#      build inlines it at compile time. (Dev fork: no Supabase keys; sign-in is
#      Microsoft Entra via MSAL, configured at runtime from the backend's
#      GET /config.)
#   3. Runs `pnpm install` if node_modules is missing.
#   4. Checks the Mike backend is reachable and reports its auth mode.
#   5. Verifies port 3200 is free — the dev server + manifest are hardwired to
#      it, and the Mike web app on :3000 collides. Fails fast with a fix.
#   6. Installs the trusted dev HTTPS certificate if Word doesn't already trust
#      it (this step may prompt for your keychain/admin password).
#   7. Sources the env and runs `pnpm start`, which boots the webpack dev server
#      on https://localhost:3200 and sideloads the add-in into Word desktop.
#
# Prerequisite: the Mike API must be running (`pnpm dev` in backend/) with
# AUTH_PROVIDER=entra (and the Entra app registration set up per
# word-addin/README.md) or AUTH_PROVIDER=local for a no-Entra dev login.
#
# Pass --setup-only to do everything except the port check + final `pnpm start`.
#
set -euo pipefail

SETUP_ONLY=0
[ "${1:-}" = "--setup-only" ] && SETUP_ONLY=1

cd "$(dirname "$0")/.."          # -> word-addin
ADDIN_DIR="$(pwd)"
ROOT_DIR="$(cd .. && pwd)"       # -> repo root (word-addin lives at the root)

step() { printf "\n\033[1;34m==> %s\033[0m\n" "$1"; }
ok()   { printf "    \033[1;32m✔\033[0m %s\n" "$1"; }
warn() { printf "    \033[1;33m! %s\033[0m\n" "$1"; }

# ── 1. Prerequisites ─────────────────────────────────────────────────────────
step "Checking prerequisites"
command -v node >/dev/null 2>&1 || { echo "Node.js 22+ is required (https://nodejs.org)"; exit 1; }
NODE_MAJOR="$(node --version | sed -E 's/^v([0-9]+).*/\1/')"
[ "$NODE_MAJOR" -ge 22 ] || { echo "Node.js 22+ is required; found $(node --version)"; exit 1; }
ok "node $(node --version)"

# ── 2. Read the backend origin from frontend/.env.local ──────────────────────
# The add-in talks to the SAME backend as the web app, so we reuse the web
# app's env file. NEXT_PUBLIC_API_BASE_URL is the backend ORIGIN (the add-in
# appends /api and /config itself, like the web frontend).
step "Reading the backend origin from frontend/.env.local"
FE_ENV="$ROOT_DIR/frontend/.env.local"
read_env() { [ -f "$FE_ENV" ] && grep -E "^$1=" "$FE_ENV" | head -1 | cut -d= -f2- | tr -d '"' || true; }
API_BASE="${API_PROXY_TARGET:-$(read_env NEXT_PUBLIC_API_BASE_URL)}"
API_BASE="${API_BASE:-http://localhost:3001}"
API_BASE="${API_BASE%/}"
ok "backend origin: $API_BASE"

# ── 3. Write .env ─────────────────────────────────────────────────
# The add-in is served over HTTPS (Word requires it). The local backend is HTTP,
# which Word's WebView blocks as mixed content, so the bundle points at the
# SAME-ORIGIN HTTPS dev server, which proxies /api and /config to the real
# backend (see the proxy config in webpack.config.js). Same-origin also
# side-steps the backend's CORS allow-list (FRONTEND_URL only).
step "Configuring .env (proxied through the HTTPS dev server)"
DEV_ORIGIN="https://localhost:3200"
cat > .env <<EOF
# Generated by scripts/dev.sh. The URL points at the dev server's HTTPS proxy
# (webpack.config.js) so the task pane never makes blocked HTTP / cross-origin
# requests. The real backend is reached via API_PROXY_TARGET, exported below
# before pnpm start. No identity values here: Entra tenant / client / scope
# come from the backend's GET /config at runtime.
REACT_APP_API_BASE_URL=${DEV_ORIGIN}
EOF
ok "wrote proxied backend URL"

# ── 4. Dependencies ──────────────────────────────────────────────────────────
step "Installing dependencies"
if [ -d node_modules ]; then
    ok "node_modules present (run 'pnpm install' manually to update)"
else
    pnpm install
    ok "dependencies installed"
fi

# ── 5. Mike backend health + auth mode ───────────────────────────────────────
# The add-in is useless without the API: sign-in config comes from its
# GET /config, and chat, actions, workflows, project browsing, and uploads call
# the Mike API.
step "Checking the Mike backend is running"
BACKEND_OK=1

# 5a. Mike backend — GET /api/health returns {"ok":true}.
health_code="$(curl -s -m6 -o /dev/null -w '%{http_code}' "$API_BASE/api/health" 2>/dev/null)" || true
[ -n "$health_code" ] || health_code=000
if [ "$health_code" = "200" ]; then
    ok "Mike backend healthy at $API_BASE"
else
    BACKEND_OK=0
    warn "Mike API NOT reachable at $API_BASE (HTTP $health_code)."
    warn "Start it:  cd backend && pnpm dev"
fi

# 5b. Auth mode — the add-in supports AUTH_PROVIDER=entra (MSAL) and local.
if [ "$BACKEND_OK" = 1 ]; then
    auth_mode="$(curl -s -m6 "$API_BASE/config" 2>/dev/null | sed -nE 's/.*"authProvider":"([a-z]+)".*/\1/p')" || true
    case "$auth_mode" in
        entra) ok "auth mode: entra (Sign in with Microsoft — see README → Entra app registration)" ;;
        local) ok "auth mode: local (development email login)" ;;
        *) warn "auth mode '${auth_mode:-unknown}' — the add-in needs AUTH_PROVIDER=entra or local." ;;
    esac
fi

# ── 6. Port 3200 availability ─────────────────────────────────────────────────
# The webpack dev server AND the add-in manifest are hardwired to
# https://localhost:3200. Fail fast with a clear message BEFORE the cert prompt /
# launch — otherwise `npm start` dies with an opaque EADDRINUSE.
# (Skipped for --setup-only, which never launches; re-running while the add-in's
# own server is already up correctly trips this too.)
if [ "$SETUP_ONLY" != 1 ]; then
    step "Checking port 3200 is free"
    if command -v lsof >/dev/null 2>&1 && lsof -nP -iTCP:3200 -sTCP:LISTEN >/dev/null 2>&1; then
        holder="$(lsof -nP -iTCP:3200 -sTCP:LISTEN 2>/dev/null | awk 'NR==2{print $1" (pid "$2")"}')"
        warn "Port 3200 is already in use by: ${holder:-another process}"
        echo "    The add-in dev server and Word's manifest both require https://localhost:3200."
        echo "    Stop the process using it first:"
        echo "      lsof -nP -iTCP:3200 -sTCP:LISTEN     # confirm what it is"
        echo "    Then re-run this script."
        exit 1
    fi
    ok "port 3200 is free"
fi

# ── 7. Dev HTTPS certificate ─────────────────────────────────────────────────
# office-addin-dev-certs regenerates the certificate (AND a new signing CA)
# whenever the old one expires (~30 days) — the webpack dev server triggers
# this silently on startup. The tool's own `verify` only checks that a CA *by
# that name* exists in the trust store, so after a regeneration it reports
# "trusted" while the OS actually trusts the OLD CA — and Word rejects the
# pane with "content is blocked because it isn't signed by a valid security
# certificate". Verify the ACTUAL chain against the OS trust store instead,
# and force a real reinstall when it has drifted.
step "Checking dev HTTPS certificate"
CERT_DIR="$HOME/.office-addin-dev-certs"
cert_trusted() {
    [ -f "$CERT_DIR/localhost.crt" ] || return 1
    if [ "$(uname)" = "Darwin" ]; then
        # Ground truth: does macOS trust this exact leaf for SSL on localhost?
        security verify-cert -c "$CERT_DIR/localhost.crt" -p ssl -s localhost >/dev/null 2>&1
    else
        npx --no-install office-addin-dev-certs verify >/dev/null 2>&1
    fi
}
if cert_trusted; then
    ok "dev certificate trusted (verified against the OS trust store)"
else
    warn "Dev certificate is missing, expired, or signed by a CA the OS no longer trusts."
    warn "Reinstalling — this may prompt for your keychain/admin password…"
    # `install` skips itself when its name-based verify passes — which is
    # exactly the drift case — so uninstall first to force a real install.
    npx office-addin-dev-certs uninstall >/dev/null 2>&1 || true
    npx office-addin-dev-certs install || true
    if ! cert_trusted && [ "$(uname)" = "Darwin" ] && [ -f "$CERT_DIR/ca.crt" ]; then
        # Last resort: trust the current CA directly.
        warn "Trusting the current dev CA directly (keychain prompt)…"
        security add-trusted-cert -r trustRoot \
            -k "$HOME/Library/Keychains/login.keychain-db" "$CERT_DIR/ca.crt" || true
    fi
    if cert_trusted; then
        warn "Cert trusted — fully QUIT Word (Cmd-Q) before launching so it reloads trust."
    else
        warn "Certificate STILL not trusted — Word will refuse the pane."
        warn "See word-addin/README.md → Troubleshooting → certificate trust drift."
        exit 1
    fi
fi

# ── 8. Launch ────────────────────────────────────────────────────────────────
if [ "$SETUP_ONLY" = 1 ]; then
    step "Setup complete"
    [ "$BACKEND_OK" = 1 ] || warn "Backend is not fully up — start Mike before launching (see above)."
    echo "    To launch: cd $ADDIN_DIR && set -a && source .env && set +a && API_PROXY_TARGET=$API_BASE pnpm start"
    exit 0
fi

if [ "$BACKEND_OK" != 1 ]; then
    step "Mike backend is not running"
    echo "    The add-in needs Mike running before it does anything useful. Start it:"
    echo "      (backend/)    pnpm dev           # the Mike API on :3001"
    echo "    with AUTH_PROVIDER=entra (see README → Entra app registration) or local."
    echo "    Then re-run this script. To launch anyway, set FORCE=1 (sign-in will fail until Mike is up)."
    [ "${FORCE:-0}" = 1 ] || exit 1
    warn "FORCE=1 set — launching despite the backend being down."
fi

# Clear any stale sideload registration BEFORE launching. office-addin-debugging
# registers the add-in by hard-linking manifest.xml into Word's sideload folder
# (~/Library/Containers/com.microsoft.Word/Data/Documents/wef). If a previous run
# exited without `npm run stop` (a crash, a Ctrl-C, a killed terminal), that link
# is left behind — and the next `npm start` dies with
# "EEXIST: file already exists, link 'manifest.xml' -> '…/wef/<id>.manifest.xml'".
# A best-effort stop makes re-runs genuinely idempotent (it also shuts down any
# orphaned dev server from that prior run). Errors are ignored: a clean machine
# with nothing registered is the normal case.
step "Clearing any stale add-in registration"
pnpm run stop >/dev/null 2>&1 || true
ok "ready to (re)register the add-in"

step "Starting dev server + sideloading into Word"
echo "    (webpack serves https://localhost:3200 and proxies /api + /config to the"
echo "     real backend; Word opens with the add-in.)"
echo "    In Word: Home → Mike Legal AI → Open Mike"
# Tell webpack where to proxy backend calls (tracks the real backend URL).
export API_PROXY_TARGET="$API_BASE"
set -a
# shellcheck disable=SC1091
source .env
set +a
exec pnpm start
